$(function(){
	$('#nav').on({
	click:function(){
		if($(this).text()=='首页'){
	        $('#content').load('./pages/shouye.html');
			}
		if($(this).text()=='商家管理'){
	        $('#content').load('./pages/bussiness.html');
			}
		if($(this).text()=='招聘管理'){
	        $('#content').load('./pages/zhaopin.html');
			}
		if($(this).text()=='用户管理'){
	        $('#content').load('./pages/user.html');
			}
		if($(this).text()=='模块管理'){
	        $('#content').load('./pages/modal.html');
			}
		if($(this).text()=='客服管理'){
	        $('#content').load('./pages/customer.html');
			}
		if($(this).text()=='审核模块'){
	        $('#content').load('./pages/audit.html');
			}
		if($(this).text()=='求职联系'){
	        $('#content').load('./pages/jobhunter.html');
			}
	}
	},'span')
})